travis:
  secure:
    BINSTAR_TOKEN: Q4LN8zaJNm1bXaaUpZnx0jrRgCgyrwseTQNxBDwuOTApmyHIuonA79NBgofreK9NJkJyR9UWxv6AuYIMYttvcSkbnoGGHqFXRKlv8oolbaP9wCzirKBZ5HbIS4ef5+ULkp6DuxTNVWSxXGirC5xcbhO269NfLzF3h9vsjMgzwFiS9YTJyUgELuDLFea7qyqOuP1AZ25srQ4He+nYvegVdFZJFiB4EY5CdC1uiTPQjyAjccFRc7+BbFyRzeqmBbwxGqppoTxnL8r8ZLY54nmPccEotnLboEZ6r/1HSZDWpbZGTgKFzUw0C9goTTaJkX052TRF4xZX7kkgn/k78pNIUei5CMnbalYNXYjzr47ZZUcbEeV+pSRANiLPQEGnaWbx1Vf3fGcNYDmYzrYHxDfeP1x/7ZXga8Ff/VM3mXNxLT/zkKZ2MuK9fBirf/HurkxeV6bhKzuBODAPd1HqSMAqmlxYa/+0NAU7Xs7R3NmnEqdOjo4je8MncYbmZyevdKt10IEdEKvBKgf8VI5FWyRd+ua2bCArodOhDosdPx5qpsuZXKleJpioukc4Ky0Bmbv2vbuCf2pt2KpVb09l4t8UgbTyxNIdg/DZeCmuZZgCdkC3adn2z1K6+89uTqOtBAowAL9jjWs3D3vOdyVejM5iPQ9MufEkN3td7hz5FWfAhg0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
